### PR TITLE
feature/get-list

### PR DESCRIPTION
**Pull request by h314to**
I ended up not using Actors, because it would overcomplicate things significantly. Please note that in order to run this you must have the twitter keys configuration file (sent by Slack) in the correct folder (src/main/resources/).

### CODE REVIEW

**Review by coppetti — APPROVED** [review]

**Review by alesr — APPROVED** [review]
Well done Agapito! I've tested here, and the code looks great.

Question: Should `src/main/target/` be aded to `.gitignore`?

**Comment by h314to** [comment]
No need to exclude the resources dir because I'm explicitly excluding the config file in .gitignore. The dir might be useful for other stuff (e.g., other non-sensitive config files) we may want to track with git.

**Comment by alesr** [comment]
@h314to not the `resources` but  `src/main/target/`. I get some scala stuff to commit after executing the code.

screen shot 2017-02-03 at 09 42 11

**Review by m-maga — APPROVED** [review]

**Comment by h314to** [comment]
Sorry, misread. That's a strange place for traget/. On my machine it is located on the repo top level

`~/Development/Bacon/twitter-lm-extractor$ls`
`README.md  build.sbt  project  src  target`

Yes, target/ is ok to exclude from anywhere. I'll update .gitignore

**Pull request merged**
