### PR TITLE
Added linter (scalastyle)

### PR DESCRIPTION
**Pull request by h314to**
* moved source and tests from 'scala-2.11' to 'scala'. That's
  where they should be, and scalastyle doensn't find them in 'scala-2.11'.

### CODE REVIEW

**Comment by h314to** [comment]
The scalastyle config file is in the project/ folder because this way intellij automatically displays warnings.

**Comment by alesr** [comment]
Is there any way to run the linter without running the unit tests?

**Comment by h314to** [comment]
Yes, that's exactly what this does:
`  sbt scalastyle`

That checks `src/main/*`. To check `src/test/*`  we run
`  sbt test:scalastyle`
which checks the tests' code without actually running them.

We could also use the [overcommit hook](http://www.scalastyle.org/git-pre-commit-hook.html) to run the linter locally on each commit, but IntelliJ already nags you about the scalastyle stuff (configured in `scalastyle-config.xml`).

**Comment by alesr** [comment]
Do I have to call the `sbt scalastyle` command explicitly with Jenkins before running the `sbt test` or Scala execute this automatically before running the unit test?

**Comment by h314to** [comment]
You have to call it explicitly. But you can run (in this order) (i) clean, (ii) scalastyle on source, (iii) scalastyle on tests, and (iv) tests with:
`  sbt -Dsbt.log.noformat=true clean scalastyle test:scalastyle test`

**Comment by alesr** [comment]
Thanks @h314to. I'll change this part in the CI with you tomorrow.

**Review by alesr — APPROVED** [review]

**Comment by h314to** [comment]
Ok. Just tested locally with
`ENTRYPOINT ["sbt", "-Dsbt.log.noformat=true", "clean", "scalastyle", "test:scalastyle", "test"]`
in the Dockerfile. It is pretty fast.

**Review by coppetti — APPROVED** [review]

**Pull request merged**
